### ISSUE TITLE
Wow brings back memories!

### ISSUE THREAD

**Issue by mallowigi** [Litarvan/tiger-idea#1]
Hey,

Désolé de t'importuner mais je voulais juste déclarer mon admiration pour avoir décidé d'implémenter un plugin pour Tiger. Je suis moi meme un développeur de plugins pour JB et j'ai fait EPITA il y'a bien longtemps et bien entendu j'ai eu Tiger comme projet (d'ailleurs je suis surpris que ca existe encore :))

**Comment by Litarvan** [comment]
Wow ! Alors ça je m'y attendais pas 😄 

Je te connaissais depuis un moment en tant qu'utilisateur habitué du Material Theme, mais je ne savais pas que tu avais fait EPITA haha. Et oui le projet existe toujours, il est obligatoire cette année !
Comme on avait des exos à faire avec le langage au début du projet, et qu'un assistant avait fait un plugin pour vim, je trouvais sympa d'en faire un pour IntelliJ/CLion. Même si ça impliquait un certains effort pour pas forcément grand chose, c'était sympa 😆 le syntax checking est franchement pratique.

Merci beaucoup pour ton message en tout cas, recevoir l'admiration de quelqu'un tel que toi ça fait vraiment plaisir 😊 je l'oublierai pas !
